### ISSUE TITLE
Morning Session Peer to peer code review

### ISSUE THREAD

**Issue by tjay1760** [rachaouldbabaali/awsome-books-ES6#2]
Dear Racha 👋 

- Congratulations on the work done to implement the project using ES6 modules. The code is readable and efficient as it uses some concepts of ES6 such as modules and use of arrow functions.  
- To improve the user experience you can also add an alert that tells the user when there are no books to show in storage.
- Also make sure to remove comments that do not serve any important purpose in the code. 
- Nonetheless you have done great work with the project
Regards 😃

**Comment by rachaouldbabaali** [comment]
Thank you for taking the time to review my work. Your feedback is greatly appreciated and I am grateful for the opportunity to learn and grow from it.

I wanted to let you know that I have taken your notes into consideration and have made the necessary changes to improve my work. Your constructive criticism has helped me to see areas where I can improve and I am committed to implementing your suggestions in my future work.

Once again, thank you for your review and for helping me to become a better insert profession or skill.
